[pytest]
minversion = 8.0
addopts = -v -s --html=report.html --self-contained-html
testpaths =
    HandsOn6_PyTest_Framework
    HandsOn7_PageObjectModel/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke test cases
    regression: Full regression test suite
    pom: Page Object Model test suite
